### ISSUE TITLE
Still have some space to improve

### ISSUE THREAD

**Issue by Xflick** [dry999/NumGuess#2]
First, there are a few bugs:
1. The first line # NumGuess. Maybe you confuse # with //. And it raises an error.
2. When I input "2476237462374623" or something like this, the program crashes. I think it is because the input is out of the range of an integer

And then, let's talk about the style of coding. Like in line 12, this line is too long, and you may cut it into two lines. And in line 18, you wrote "answer_number[0]=rand()*10/(RAND_MAX + 1);", but in line 21, you wrote "answer_number[1]=rand()*10/(RAND_MAX+1);". Why there is a space before and behind "+" in line 18 but disappears in line 21?? I think you should keep a certain style of coding, but not always changing.

**Comment by dry999** [comment]
I have fixed problem1,3 maybe I can use unsigned long [int] to solve problem
